server:
  port: 8084
  http2:
    enabled: true
  undertow:
    io-threads: 16 # IO线程数
    worker-threads: 256 # 阻塞任务线程池
    buffer-size: 1024 # 每块buffer的空间大小，越小的空间被利用越充分
    direct-buffers: true # 是否分配的直接内存(NIO直接分配的堆外内存)