# 端口
server:
  port: 80

# 注册到consul
spring:
  application:
    name: cloud-comsumer-order
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

